[package]
name = "set_efficiency_mode"
version = "1.0.0"
edition = "2024"

[profile.release]
strip = "symbols"
panic = "abort"

[dependencies]
anyhow = "1"
scopeguard = "1"
windows = { version = "0", features = [
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
] }
