name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
          profile: minimal

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --target x86_64-pc-windows-msvc

      - name: Zip
        run: powershell Compress-Archive -Path conf.txt, target\x86_64-pc-windows-msvc\release\set_efficiency_mode.exe -DestinationPath set_efficiency_mode.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            set_efficiency_mode.zip
